# Generated by Django 5.0.6 on 2024-07-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urldata_delete_urlchecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
